<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" http-equiv="Content-Type">
    <title></title>
</head>
<body style="font-family: Arial;padding: 0;margin: 0;box-sizing: border-box;">
    <div>Kontaktanfrage</div>
    <br>
    <div>
        <div>
            <span>Name: </span>
            <span>{{firstname}} {{lastname}}</span>
        </div>
        <div>
            <span>Email: </span>
            <span>{{email}}</span>
        </div>
        <div>
            <span>Unternehmen: </span>
            <span>{{company}}</span>
        </div>
        <br>
        <div>
            <span>Nachricht: </span><br><br>
            <span>{{textarea}}</span>
        </div>
    </div>
    <br><br><br>
    {{HTTP_USER_AGENT}}
</body>
</html>